export const translations = {
  en: {
    title: "Football Data",
    language: "Language",
    leagueLabel: "League:",
    seasonLabel: "Season:",
    searchButton: "Search",
    standingsTitle: "Standings",
    topScorersTitle: "Top Scorers",
    standingsTable: {
      team: "Team",
      played: "GP",
      wins: "W",
      draws: "D",
      losses: "L",
      goalsFor: "GF",
      goalsAgainst: "GA",
      goalDiff: "+/-",
      points: "Pts",
    },
    standingsInfo: {
      played: "GP = Games Played",
      wins: "W = Wins",
      draws: "D = Draws",
      losses: "L = Losses",
      goalsFor: "GF = Goals For",
      goalsAgainst: "GA = Goals Against",
      goalDiff: "+/- = Goal Differential",
      points: "Pts = Points",
    },
    topScorersTable: {
      player: "Player",
      age: "Age",
      team: "Team",
      games: "Games",
      goals: "Goals",
      assists: "Assists",
    },
    messages: {
      loading: "Loading...",
      noData: "No data available.",
      error: "Error while loading data.",
      apiLimit: "API limit exceeded. Try again later.",
      notKnown: "Not known.",
    },
    footer: "Football Data © 2025",
    continents: {
      Europe: "Europe",
      "South-America": "South America",
      "North-America": "North America",
      Africa: "Africa",
    },
  },
  fi: {
    title: "Jalkapallotilastot",
    language: "Kieli",
    leagueLabel: "Liiga:",
    seasonLabel: "Kausi:",
    searchButton: "Hae",
    standingsTitle: "Sarjataulukko",
    topScorersTitle: "Parhaat maalintekijät",
    standingsTable: {
      team: "Joukkue",
      played: "PO",
      wins: "V",
      draws: "T",
      losses: "H",
      goalsFor: "TM",
      goalsAgainst: "PM",
      goalDiff: "+/-",
      points: "P",
    },
    standingsInfo: {
      played: "PO = Pelatut ottelut",
      wins: "V = Voitot",
      draws: "T = Tasapelit",
      losses: "H = Häviöt",
      goalsFor: "TM = Tehdyt maalit",
      goalsAgainst: "PM = Päästetyt maalit",
      goalDiff: "+/- = Maaliero",
      points: "P = Pisteet",
    },
    topScorersTable: {
      player: "Pelaaja",
      age: "Ikä",
      team: "Joukkue",
      games: "Ottelut",
      goals: "Maalit",
      assists: "Syötöt",
    },
    messages: {
      loading: "Ladataan...",
      noData: "Ei tietoja saatavilla.",
      error: "Virhe ladattaessa tietoja.",
      apiLimit: "API-raja ylittyi. Yritä uudelleen myöhemmin.",
      notKnown: "Ei tiedossa.",
    },
    footer: "Jalkapallotilastot",
    continents: {
      Europe: "Eurooppa",
      "South-America": "Etelä-Amerikka",
      "North-America": "Pohjois-Amerikka",
      Africa: "Afrikka",
    },
  },
  sv: {
    title: "Fotbollsstatistik",
    language: "Språk",
    leagueLabel: "Liga:",
    seasonLabel: "Säsong:",
    searchButton: "Sök",
    standingsTitle: "Tabell",
    topScorersTitle: "Toppskyttar",
    standingsTable: {
      team: "Lag",
      played: "SP",
      wins: "V",
      draws: "O",
      losses: "F",
      goalsFor: "GM",
      goalsAgainst: "IM",
      goalDiff: "+/-",
      points: "P",
    },
    standingsInfo: {
      played: "SP = Spelade matcher",
      wins: "V = Vinster",
      draws: "O = Oavgjorda",
      losses: "F = Förluster",
      goalsFor: "GM = Gjorda mål",
      goalsAgainst: "IM = Insläppta mål",
      goalDiff: "+/- = Målskillnad",
      points: "P = Poäng",
    },
    topScorersTable: {
      player: "Spelare",
      age: "Ålder",
      team: "Lag",
      games: "Matcher",
      goals: "Mål",
      assists: "Assist",
    },
    messages: {
      loading: "Laddar...",
      noData: "Ingen data tillgänglig.",
      error: "Fel vid laddning av data.",
      apiLimit: "API-gränsen överskriden. Försök igen senare.",
      notKnown: "Okänt.",
    },
    footer: "Fotbollsstatistik",
    continents: {
      Europe: "Europa",
      "South-America": "Sydamerika",
      "North-America": "Nordamerika",
      Africa: "Afrika",
    },
  },
};